-- Drop the existing table if it exists
DROP TABLE IF EXISTS orders;

-- Create the orders table with the exact schema shown
CREATE TABLE orders (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    items JSONB,
    total NUMERIC,
    status TEXT,
    payment_method TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows all operations
CREATE POLICY "Enable all access" ON orders FOR ALL USING (true);

